"""create all tables

Revision ID: 04d6cbcce89a
Revises:
Create Date: 2026-07-23 00:18:51.838608

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04d6cbcce89a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('team_namespace', sa.String(length=100), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('password_history', sa.JSON(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agent_classes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_namespace', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alertrules_enabled', 'alert_rules', ['enabled'], unique=False)
    op.create_index('idx_alertrules_type', 'alert_rules', ['alert_type'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_events', ['actor_type', 'actor_id'], unique=False)
    op.create_index('idx_audit_time', 'audit_events', ['created_at'], unique=False)
    op.create_index('idx_audit_type', 'audit_events', ['event_type'], unique=False)
    op.create_index('idx_audit_type_time', 'audit_events', ['event_type', 'created_at'], unique=False)
    op.create_table('background_tasks',
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bgtasks_celery', 'background_tasks', ['celery_task_id'], unique=False)
    op.create_index('idx_bgtasks_status', 'background_tasks', ['status'], unique=False)
    op.create_table('capabilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('normalized_input_schema', sa.JSON(), nullable=True),
    sa.Column('normalized_output_schema', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('migration_guidance', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_capabilities_domain', 'capabilities', ['domain'], unique=False)
    op.create_index('idx_capabilities_status', 'capabilities', ['status'], unique=False)
    op.create_table('capability_packs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_namespace', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mcp_servers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=1024), nullable=False),
    sa.Column('owner_team', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('trust_level', sa.String(length=50), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('team_namespace', sa.String(length=100), nullable=True),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decommission_phase', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opa_policy_versions',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('bundle_hash', sa.String(length=64), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deployed_by', sa.String(length=255), nullable=True),
    sa.Column('rego_content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opapolicy_version', 'opa_policy_versions', ['version'], unique=False)
    op.create_table('agent_class_packs',
    sa.Column('agent_class_id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_class_id'], ['agent_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['capability_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agentclasspack_class', 'agent_class_packs', ['agent_class_id'], unique=False)
    op.create_index('idx_agentclasspack_pack', 'agent_class_packs', ['pack_id'], unique=False)
    op.create_table('agent_identities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_class_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=512), nullable=False),
    sa.Column('token_prefix', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_from_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_class_id'], ['agent_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rotated_from_id'], ['agent_identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_identities_class', 'agent_identities', ['agent_class_id'], unique=False)
    op.create_index('idx_identities_status', 'agent_identities', ['status'], unique=False)
    op.create_index('idx_identities_token', 'agent_identities', ['token_hash'], unique=False)
    op.create_table('alert_events',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_fired', 'alert_events', ['fired_at'], unique=False)
    op.create_index('idx_alerts_rule', 'alert_events', ['rule_id'], unique=False)
    op.create_table('capability_aliases',
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index('idx_aliases_alias', 'capability_aliases', ['alias'], unique=False)
    op.create_index('idx_aliases_capability', 'capability_aliases', ['capability_id'], unique=False)
    op.create_table('capability_mappings',
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('input_mapping', sa.JSON(), nullable=True),
    sa.Column('output_mapping', sa.JSON(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('routing_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mappings_capability', 'capability_mappings', ['capability_id'], unique=False)
    op.create_index('idx_mappings_server', 'capability_mappings', ['server_id'], unique=False)
    op.create_index('idx_mappings_unique', 'capability_mappings', ['capability_id', 'server_id', 'tool_name'], unique=True)
    op.create_table('pack_assignments',
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['capability_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_packassignment_capability', 'pack_assignments', ['capability_id'], unique=False)
    op.create_index('idx_packassignment_pack', 'pack_assignments', ['pack_id'], unique=False)
    op.create_table('routing_rules',
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routing_rules_cap', 'routing_rules', ['capability_id'], unique=False)
    op.create_index('idx_routing_rules_server', 'routing_rules', ['server_id'], unique=False)
    op.create_table('server_tools',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tools_server', 'server_tools', ['server_id'], unique=False)
    op.create_index('idx_tools_server_tool', 'server_tools', ['server_id', 'tool_name'], unique=True)
    op.create_table('tool_versions',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('is_breaking', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_versions_server', 'tool_versions', ['server_id', 'tool_name'], unique=False)
    op.create_table('trust_assignments',
    sa.Column('agent_class_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('trust_level', sa.String(length=50), nullable=False),
    sa.Column('tool_scope', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_class_id'], ['agent_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trust_class', 'trust_assignments', ['agent_class_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('agent_identity_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('approver_note', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_identity_id'], ['agent_identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approvals_agent', 'approval_requests', ['agent_identity_id'], unique=False)
    op.create_index('idx_approvals_status', 'approval_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_approvals_status', table_name='approval_requests')
    op.drop_index('idx_approvals_agent', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('idx_trust_class', table_name='trust_assignments')
    op.drop_table('trust_assignments')
    op.drop_index('idx_tool_versions_server', table_name='tool_versions')
    op.drop_table('tool_versions')
    op.drop_index('idx_tools_server_tool', table_name='server_tools')
    op.drop_index('idx_tools_server', table_name='server_tools')
    op.drop_table('server_tools')
    op.drop_index('idx_routing_rules_server', table_name='routing_rules')
    op.drop_index('idx_routing_rules_cap', table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index('idx_packassignment_pack', table_name='pack_assignments')
    op.drop_index('idx_packassignment_capability', table_name='pack_assignments')
    op.drop_table('pack_assignments')
    op.drop_index('idx_mappings_unique', table_name='capability_mappings')
    op.drop_index('idx_mappings_server', table_name='capability_mappings')
    op.drop_index('idx_mappings_capability', table_name='capability_mappings')
    op.drop_table('capability_mappings')
    op.drop_index('idx_aliases_capability', table_name='capability_aliases')
    op.drop_index('idx_aliases_alias', table_name='capability_aliases')
    op.drop_table('capability_aliases')
    op.drop_index('idx_alerts_rule', table_name='alert_events')
    op.drop_index('idx_alerts_fired', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('idx_identities_token', table_name='agent_identities')
    op.drop_index('idx_identities_status', table_name='agent_identities')
    op.drop_index('idx_identities_class', table_name='agent_identities')
    op.drop_table('agent_identities')
    op.drop_index('idx_agentclasspack_pack', table_name='agent_class_packs')
    op.drop_index('idx_agentclasspack_class', table_name='agent_class_packs')
    op.drop_table('agent_class_packs')
    op.drop_index('idx_opapolicy_version', table_name='opa_policy_versions')
    op.drop_table('opa_policy_versions')
    op.drop_table('mcp_servers')
    op.drop_table('capability_packs')
    op.drop_index('idx_capabilities_status', table_name='capabilities')
    op.drop_index('idx_capabilities_domain', table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index('idx_bgtasks_status', table_name='background_tasks')
    op.drop_index('idx_bgtasks_celery', table_name='background_tasks')
    op.drop_table('background_tasks')
    op.drop_index('idx_audit_type_time', table_name='audit_events')
    op.drop_index('idx_audit_type', table_name='audit_events')
    op.drop_index('idx_audit_time', table_name='audit_events')
    op.drop_index('idx_audit_actor', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('idx_alertrules_type', table_name='alert_rules')
    op.drop_index('idx_alertrules_enabled', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_table('agent_classes')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
